---
# Keepalived config
keepalived_bind_interface: eth0
keepalived_vip: 172.16.42.20

# HAProxy setting
haproxy_bind_address: 172.16.42.20
haproxy_balancing_servers:
  - { name: 's1', ip: "172.16.42.12" }
  - { name: 's2', ip: "172.16.42.13" }

# hatop
hatop_version: 0.7.7
hatop_src_dir: /tmp
hatop_install_dir: /usr/local/bin
hatop_archive_name: "hatop-{{ hatop_version }}.tar.gz"
hatop_dir_name: "hatop-{{ hatop_version }}"
hatop_download_url: "https://storage.googleapis.com/google-code-archive-downloads/v2/code.google.com/hatop/{{ hatop_dir_name }}.tar.gz"
