---
- name: Initialize the Kubernetes cluster
  shell: kubeadm init --config=/tmp/kubeadm-config.yaml
  #command: kubeadm init --apiserver-advertise-address="{{ nodes_network | ipaddr('10') | ipaddr('address') }}" --apiserver-cert-extra-sans="{{ nodes_network | ipaddr('10') | ipaddr('address') }}" --pod-network-cidr="{{ pods_network }}" --upload-certs

- name: Copy kubeconfig for vagrant
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - cp -i /etc/kubernetes/admin.conf /vagrant/admin.conf
    - chown vagrant:vagrant /home/vagrant/.kube/config /vagrant/admin.conf
