---
- hosts: all
  become: true
  tasks:
    - include: common.yml

    - name: Initialize the Kubernetes cluster using kubeadm
      command: kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10" --pod-network-cidr=172.16.0.0/16 --upload-certs

    - name: Setup kubeconfig for vagrant user
      command: "{{ item }}"
      with_items:
        - mkdir -p /home/vagrant/.kube
        - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
        - cp -i /etc/kubernetes/admin.conf /vagrant/admin.conf
        - chown vagrant:vagrant /home/vagrant/.kube/config /vagrant/admin.conf

    - name: Install calico pod network
      become: false
      shell: |
        wget https://docs.projectcalico.org/v3.10/manifests/calico.yaml -O calico.yaml
        sed -i "s/192.168.0.0/'"172.16.0.0/16"'/g" calico.yaml
        kubectl apply -f calico.yaml

    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      become: false
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

  handlers:
    - name: docker status
      service: name=docker state=started
