---
- hosts: all
  become: true
  roles:
    - docker
    - swap
    - k8s
    - iptables
    - kubelet  
    - k8s/init-cluster
    - calico
    - metallb
    - traefik
    - k8s-dashboard
    - k8s/create-join
    - k8s/fetch-keys
  
  handlers:
    - name: docker status
      service: name=docker state=started
