---
- hosts: all
  become: true
  roles:
    - docker
    - swap
    - iptables
    - k8s/install
    - kubelet  
    - k8s/join-cluster
  
  handlers:
    - name: docker status
      service: name=docker state=started
