---
- hosts: all
  become: true
  roles:
    - docker
    - swap
    - k8s
    - iptables
    - kubelet  
    - k8s/join-cluster
  handlers:
    - name: docker status
      service: name=docker state=started
