apiVersion: kubeadm.k8s.io/v1alpha2
kind: MasterConfiguration
kubernetesVersion: v1.16.0
networking:
  podSubnet: {{pods_network}}
apiServerCertSANs:
- 192.168.50.10
- 192.168.50.11
- 192.168.50.12
- localhost
etcd:
  endpoints:
  - https://192.168.50.10:2379
  - https://192.168.50.11:2379
  - https://192.168.50.12:2379
  caFile: /etc/kubernetes/pki/etcd/ca.pem
  certFile: /etc/kubernetes/pki/etcd/client.pem
  keyFile: /etc/kubernetes/pki/etcd/client-key.pem
apiServerExtraArgs:
  endpoint-reconciler-type: lease
