---
- name: Initialize the Kubernetes cluster
  command: kubeadm init --apiserver-advertise-address="192.168.50.10" --apiserver-cert-extra-sans="192.168.50.10" --pod-network-cidr=172.16.0.0/16 --upload-certs

- name: Copy kubeconfig for vagrant
  command: "{{ item }}"
  with_items:
    - mkdir -p /home/vagrant/.kube
    - cp -i /etc/kubernetes/admin.conf /home/vagrant/.kube/config
    - cp -i /etc/kubernetes/admin.conf /vagrant/admin.conf
    - chown vagrant:vagrant /home/vagrant/.kube/config /vagrant/admin.conf
